CREATE TABLE queue (
  ID TEXT PRIMARY KEY,
  Domain TEXT NOT NULL
);

CREATE TABLE node (
  ID TEXT PRIMARY KEY,
  Url TEXT NOT NULL,
  QueueID TEXT REFERENCES queue(ID)
);

CREATE TABLE visited_node (
  ID TEXT PRIMARY KEY,
  Url TEXT NOT NULL,
  NodeID TEXT REFERENCES node(ID)
);

