CREATE TABLE Queue (
  ID TEXT PRIMARY KEY,
  Domain TEXT NOT NULL
);

CREATE TABLE Node (
  ID TEXT PRIMARY KEY,
  Url TEXT NOT NULL,
  QueueID TEXT REFERENCES Queue(ID)
);

CREATE TABLE VisitedNode (
  ID TEXT PRIMARY KEY,
  Url TEXT NOT NULL,
  NodeID TEXT REFERENCES Node(ID)
);

