services:
  rabbitmq:
    image: rabbitmq
    healthcheck: &healthcheck
      test: ["CMD","echo","Testing"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - zennet
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_START_VNC=false
    healthcheck:
    <<: *healthcheck
    networks:
      - zennet



  web:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on: &depends
      rabbitmq:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    networks:
      - zennet

  db:
    build:
      context: ./database-service/
      dockerfile: Dockerfile
    depends_on:
      <<: *depends
    networks:
      - zennet
    volumes:
      - db_volume:/zensearch_volume/data

  searchengine:
    build:
      context: ./search-engine-service/
      dockerfile: Dockerfile
    depends_on:
      <<: *depends
    networks:
      - zennet

  crawler:
    build:
      context: ./web-crawler-service/
      dockerfile: Dockerfile
    depends_on:
      <<: *depends
      selenium:
        conditioni: service_healthy
        restart: true
    networks:
        - zennet

networks:
  zennet:
    driver: bridge
volumes:
  db_volume:
