services:
  test:
    build:
      context: .
      dockerfile: crawler.test.dockerfile
    depends_on:
      selenium:
        condition: service_healthy
        restart: true
    networks:
      - crawler_test
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_START_VNC=false
    networks:
      - crawler_test
    healthcheck:
      test: ["CMD","echo","Running selenium healthcheck"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  crawler_test:
    driver: bridge
